import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { registerSW } from 'virtual:pwa-register'
import './index.css'
import App from './App.tsx'

// Register the Service Worker generated by vite-plugin-pwa.
// autoUpdate: new SW activates silently when all tabs are closed (no prompt needed).
registerSW({
  immediate: true,
  onRegistered(r) {
    // Check for SW updates every 60 minutes (useful for long visitor sessions)
    if (r) setInterval(() => { void r.update() }, 60 * 60 * 1000)
  },
  onOfflineReady() {
    console.info('[SW] App ready to work offline')
  },
})

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
